# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

pool:
  vmImage: 'ubuntu-latest'

variables:
  solution: '**/*.sln'
  buildConfiguration: 'Release'

parameters:
  - name: buildProject
    displayName: 'Please select the project you want to build'
    type: string
    values:
    - NONE
    - MiCake.AutoMapper
    - MiCake.Dapper
    - MiCake.DDD.CQS
    - MiCake.Identity.Authentication.JwtToken
    - MiCake.MessageBus
    - MiCake.SQLReader
    - All
  - name: buildStartProject
    displayName: 'Do you want to build and push MiCake.AspNetCore.Start'
    type: boolean 
    defalut: false
  

steps:
- task: UseDotNet@2
  displayName: 'Set current .NET version to $(dotnet_version)'
  inputs:
    packageType: 'sdk'
    version: '$(dotnet_version)'

- ${{ if eq(parameters.buildProject, 'All') }}:
  - task: DotNetCoreCLI@2
    displayName: 'Package All project to nuget.'
    inputs:
      command: 'pack'
      packagesToPack: '$(Build.SourcesDirectory)/src/core/**/*.csproj'
      versioningScheme: 'byPrereleaseNumber'
      majorVersion: '$(nuget_version_major)'
      minorVersion: '$(nuget_version_minor)'
      patchVersion: '$(nuget_version_patch)'
- ${{ elseif eq(parameters.buildProject, 'NONE') }}:

- ${{ else }}:
  - script: echo '$(Build.SourcesDirectory)/src/framework/core/${{ parameters.buildProject }}/${{ parameters.buildProject }}.csproj'
  - task: DotNetCoreCLI@2
    displayName: 'Package ${{ parameters.buildProject }} project to nuget.'
    inputs:
      command: 'pack'
      packagesToPack: '$(Build.SourcesDirectory)/src/core/${{ parameters.buildProject }}/${{ parameters.buildProject }}.csproj'
      versioningScheme: 'byPrereleaseNumber'
      majorVersion: '$(nuget_version_major)'
      minorVersion: '$(nuget_version_minor)'
      patchVersion: '$(nuget_version_patch)'

- ${{ if eq(parameters.buildStartProject) }}:
  - task: DotNetCoreCLI@2
    displayName: 'Package MiCake.AspNetCore.Start project to nuget.'
    inputs:
      command: 'pack'
      packagesToPack: '$(Build.SourcesDirectory)/src/starter/**/*.csproj'
      versioningScheme: 'byPrereleaseNumber'
      majorVersion: '$(nuget_version_major)'
      minorVersion: '$(nuget_version_minor)'
      patchVersion: '$(nuget_version_patch)'

- task: NuGetCommand@2
  displayName: 'Push nuget packages to nuget.org'
  inputs:
    command: 'push'
    packagesToPush: '$(Build.ArtifactStagingDirectory)/**/*.nupkg;!$(Build.ArtifactStagingDirectory)/**/*.symbols.nupkg'
    nuGetFeedType: 'external'
    publishFeedCredentials: 'MiCake_NuGet_Key'
